import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Octokit } from "@octokit/core";
import { useEffect, useState } from "react";

export default function Home() {
  const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN })
  const [branches, setBranches] = useState([]);
  const [commits, setCommits] = useState({});

    const fetchBranchData = async() => {
      const response = await octokit.request('GET /repos/{owner}/{repo}/branches', {
        owner: 'schen7239',
        repo: 'test'
      })
      setBranches(response);
      console.log(response);
    }
    const fetchBranchCommits = async(commit) => {
      const response = await octokit.request('GET https://api.github.com/repos/{owner}/{repo}/commits?per_page=100&sha={sha}', {
        owner: 'schen7239',
        repo: 'test',
        sha: commit.sha,
      })
      return response;
    }

    const fetchAllBranchCommits = async() => {
      const branchCommits = await Promise.all(branches?.data?.map(async ({ name, commit }) => ({
        name: name,
        data: await fetchBranchCommits(commit)
      })))
      setCommits(branchCommits);
      console.log(commits);
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <button onClick={() => {
         fetchBranchData()
       }
       }>GET BRANCH DATA</button>
       <button onClick={() => {
         fetchAllBranchCommits()
       }}>GET BRANCH COMMITS</button>
        
    </div>
  );
}
